services:
  postgres:
    image: postgres:16
    container_name: wonga_postgres
    restart: always
    environment:
      POSTGRES_DB: wongaAssessment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Api/dockerfile
    container_name: wonga_api
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=wongaAssessment;Username=postgres;Password=1234
    ports:
      - "5027:8080"

  frontend:
    build:
      context: ./ClientApp/WongaAssessment
      dockerfile: dockerfile
    container_name: wonga_frontend
    depends_on:
      - api
    ports:
      - "3000:80"
    

volumes:
  postgres_data: